### ISSUE TITLE
Awesome Project 

### ISSUE THREAD

**Issue by swagkarna** [hdm/deepmac-tracker#1]
Awesome Project sir. You are the founder of metasploit right?

**Comment by DeepMac** [comment]
@hdm is the founder and creator of Metasploit. DeepMac is an independent project I created, HDM is using it as a source for his own hardware address forensics combined with WireShark data.
Original DeepMac project is over at https://github.com/DeepMac/deepmac

**Comment by hdm** [comment]
Hello! Please dont post messages as issues! The README covers this project's background.
